### ISSUE TITLE
Source URLs should use the correct Bioconductor version

### ISSUE THREAD

**Issue by verdurin** [fizwit/easy_update#20]
With the latest release, I found that several of the listed extensions lacked checksums so I was adding them manually. Then I saw that the source URLs had not been updated with the stated Bioconductor version - 3.9, and were still using the previous value (from the easyconfig that I was using as a source) i.e. 3.8.

**Comment by fizwit** [comment]
#### WARNING
easy_update ignores source_urls links in the easyconfig. Instead, it goes directly to CRAN, BioCondutor and or PyPi.  Easy_Update uses the value of **biocver** to determine which version of  BioConductor to query. So there could potentially be a mismatch between the EasyConfig and output from Easy_Update because eb uses the ```source_urls``` and easy_update uses ```biocver```. 

BioConductor versions are handled correctly now with --search.
When updating an R easyconfig the **biocver** parameter needs to be defined.
#### biocver defined in easyconfig
```
name = 'R'
version = '3.6.1'
versionsuffix='-generic'
biocver = '3.10'
```
 
#### Example of searching BioConductor
```
./easy_update.py --rver 3.6 --biocver 3.9 --search S4Vectors
    ('BiocGenerics', '0.30.0'),
    ('S4Vectors', '0.22.1'),

./easy_update.py --rver 3.6 --biocver 3.10  --search S4Vectors
    ('BiocGenerics', '0.31.5'),
    ('S4Vectors', '0.23.23'),
```
